default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password:
  host: localhost
  database: ajax_app_rails7_development

test:
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password:
  host: localhost
  database: ajax_app_rails7_test

production:
  adapter: postgresql
  encoding: unicode
  database: your_app_production
  pool: 5
  username: admin
  password: 2222

